version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV_VAR_NAME=VALUE
    depends_on:
      - redis_server

  redis_server:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"